# Generated by Django 2.2.7 on 2019-11-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('categoria_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=100)),
                ('url_imagen', models.URLField(verbose_name='Imagen')),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Categoria')),
            ],
        ),
    ]
