# Generated by Django 2.2.7 on 2019-11-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
