# Generated by Django 2.2.7 on 2019-11-28 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('codigo_vuelo', models.CharField(max_length=10, unique=True)),
                ('aeropuerto_llegada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeropuerto_llegada', to='vuelos.Aeropuerto')),
                ('aeropuerto_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeropuerto_salida', to='vuelos.Aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos.Cliente')),
                ('vuelo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos.Vuelo')),
            ],
        ),
    ]
