# Generated by Django 2.2.7 on 2019-11-28 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('parentesco', models.CharField(choices=[('H', 'Hijo'), ('S', 'Sobrino'), ('N', 'Nieto'), ('H', 'Hermano')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_informe', models.DateField(verbose_name='Fecha de informe')),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ParteInforme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('S', 'Sanitaria'), ('F', 'Funcional'), ('P', 'Psiquica'), ('S', 'Social'), ('T', 'Terapia Ocupacional')], max_length=1)),
                ('valoracion_inicial', models.TextField(blank=True, max_length=1200)),
                ('objetivos', models.TextField(blank=True, max_length=200)),
                ('informe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programaindividualizado.Informe')),
            ],
        ),
    ]
